OPENSTACK_FOLSOM = "Folsom"
OPENSTACK_GRIZZLY = "Grizzly on CentOS 6.4 (2013.1.2)"
OPENSTACK_CURRENT_VERSION = OPENSTACK_GRIZZLY

DEFAULT_DEPLOYMENT_TIMEOUT = 1800
DEFAULT_DEPLOYMENT_TIMEOUT_UI = 60
